Repository adityabisoi/REST-fetch, pull requests merged in 2021-03, with the labels that each got.

#27 Feature request template added
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: can-be-merged

#25 Fixed issue #2, Add issue template: bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: can-be-merged

#46 Contributor
  README.md
Labels: Level0, gssoc21

#41 Added Tech stack
  README.md
Labels: Level0, gssoc21

#44 Fixed Issue #24, Add a /tasks endpoint
  src/api/routes/tasks.ts
  src/app.ts
  src/taskdata.json
Labels: Level3, gssoc21

#15 added fake-data
  src/api/routes/users.ts
  src/fakedata.json
Labels: Level1, gssoc21

#38 Fixes Issue#16 : Dockerized the Project and Updated the README.md
  .env.example
  Dockerfile
  README.md
  docker-compose.yml
  mongo-user.sh
  src/app.ts
Labels: Level3, can-be-merged, gssoc21

#49 Made model folder for user schema and fixed imports
  src/api/models/user.ts
  src/api/routes/users.ts
  src/api/routes/usertest.ts
Labels: Level0, can-be-merged, gssoc21

#56 added photos endpoint
  data/photodata.json
  src/api/routes/photos.ts
  src/app.ts
Labels: Level3, can-be-merged, gssoc21

#55 added users delete endpoint
  src/api/routes/users.ts
Labels: Level2, can-be-merged, gssoc21

#65 Extended tasks endpoints
  src/api/routes/tasks.ts
Labels: Level3, gssoc21
