Repository adityabisoi/REST-fetch, pull requests merged in 2021-04, with the labels that each got.

#64 Create Homepage
  package-lock.json
  package.json
  src/api/routes/home.ts
  src/api/routes/tasks.ts
  src/app.ts
  src/public/favicon.ico
  src/public/fonts/terminal-font.woff
  src/public/scripts/script.js
  src/public/stylesheets/master.css
  src/views/data.js
  src/views/index.ejs
Labels: Level3, gssoc21

#70 Adding food items pictures routes
  data/photofooddata.json
  src/api/routes/foodphotos.ts
  src/app.ts
Labels: Level3, gssoc21

#80 Fixes issue #69, Add pre-commit hooks for linting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
  .github/workflows/issue.yml
  .pre-commit-config.yaml
  .prettierrc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  data/fakedata.json
  data/photodata.json
  data/photofooddata.json
  data/taskdata.json
  docker-compose.yml
  src/api/models/user.ts
  src/api/routes/foodphotos.ts
  src/api/routes/home.ts
  src/api/routes/photos.ts
  src/api/routes/tasks.ts
  src/api/routes/users.ts
  src/api/routes/usertest.ts
  src/app.ts
  src/public/stylesheets/master.css
  src/server.ts
  src/views/data.ts
Labels: Level1, gssoc21

#81 Added animals route with data
  data/animaldata.json
  src/api/routes/animals.ts
  src/app.ts
Labels: Level3, gssoc21

#82 Vehicle route
  data/vehicledata.json
  src/api/routes/vehicles.ts
  src/app.ts
Labels: Level3, gssoc21

#75 updated demo link
  README.md
Labels: Level0, bug, gssoc21

#87 added breed and picture
  src/api/routes/animals.ts
  src/api/routes/vehicles.ts
Labels: Level2, gssoc21

#88 Added extended endpoint for vehicles
  src/api/routes/vehicles.ts
Labels: Level2, gssoc21

#89 add editorconfig, close issue #66
  .editorconfig
  README.md
Labels: Level1, gssoc21

#83 added tests
  _test_/users.test.js
  package.json
Labels: Level3, gssoc21

#92 added fetch by id and group endpints in /photos
  src/api/routes/animals.ts
  src/api/routes/photos.ts
Labels: Level2, gssoc21

#54 Comments endpoint serving Get request Issue #22
  .env.example
  src/api/routes/comment.json
  src/api/routes/comments.ts
  src/app.ts
Labels: Level3, gssoc21

#98 added songdata.json and song route
  data/songdata.json
  src/api/routes/songs.ts
  src/app.ts
Labels: Level3, gssoc21

#104 added routes info on the homepage
  src/api/routes/comments.ts
  src/views/data.ts
Labels: Level2, gssoc21

#106 Extended address endpoint
  src/api/routes/address.ts
Labels: Level3, gssoc21

#105 Added endpoints in songs route
  src/api/routes/comments.ts
  src/api/routes/songs.ts
Labels: Level3, gssoc21

#108 added address and song endpoint data to homepage
  src/views/data.ts
Labels: Level2, gssoc21

#111 Added shows route
  data/showsdata.json
  src/api/routes/shows.ts
  src/app.ts
Labels: Level3, gssoc21

#112 Added books route
  data/bookdata.json
  src/api/routes/books.ts
  src/app.ts
Labels: Level3, gssoc21

#114 Updated homepage data
  src/app.ts
  src/views/data.ts
Labels: Level2, gssoc21

#117 added endpoints to books
  src/api/routes/books.ts
  src/api/routes/songs.ts
  src/views/data.ts
Labels: Level2, gssoc21

#118 Extended endpoints
  src/api/routes/shows.ts
Labels: Level2, gssoc21

#120 updated routes endpoint data
  src/views/data.ts
Labels: Level2, gssoc21
