Repository adityabisoi/REST-fetch, pull requests merged in 2021-05, with the labels that each got.

#124 added product route
  data/productdata.json
  src/api/routes/products.ts
  src/app.ts
Labels: Level3, enhancement, gssoc21

#123 Added movie route
  data/moviedata.json
  src/api/routes/movies.ts
  src/app.ts
Labels: Level3, enhancement, gssoc21

#133 Improvised animals route
  data/animaldata.json
  src/api/routes/animals.ts
Labels: Level3, gssoc21

#146 installation steps added
  README.md
Labels: Level0, documentation, gssoc21

#159 change default backend port
  src/server.ts
Labels: Level0, gssoc21

#156 links of routes added
  frontend/src/Routes.js
Labels: Level3, gssoc21

#161 changed routes to route
  frontend/src/Main.js
  frontend/src/Route.js
Labels: Level2, gssoc21

#165 added tests for contact component
  frontend/src/Contact.js
  frontend/src/contact.test.js
Labels: Level3, gssoc21

#173 added tests for contact component
  frontend/_test_/contact.test.js
  frontend/package.json
  frontend/src/Contact.js
Labels: Level3, gssoc21
